# Generated by Django 4.2 on 2024-09-24 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_subcategory_icon_subcategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent': None}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.subcategory'),
        ),
    ]
