# Generated by Django 4.2 on 2024-09-08 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_userpoint_is_active_telegramuser_point'),
        ('product', '0004_alter_product_bonus_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bonus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user.bonus'),
        ),
    ]
