# Generated by Django 4.2 on 2024-10-04 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0004_alter_product_name_alter_product_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код')),
                ('summa', models.IntegerField(default=1, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонус',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='bonus',
        ),
        migrations.CreateModel(
            name='UserSumma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.bonus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='user.telegramuser')),
            ],
        ),
        migrations.AddField(
            model_name='bonus',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='product.product'),
        ),
    ]
