# Generated by Django 4.2 on 2024-10-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_bonus_remove_product_bonus_usersumma_bonus_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersumma',
            name='bonus',
        ),
        migrations.AddField(
            model_name='usersumma',
            name='code',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
