# Generated by Django 4.2 on 2024-09-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_bonus_has_product'),
        ('product', '0006_alter_product_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bonus',
            field=models.ForeignKey(limit_choices_to={'has_product': False}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user.bonus'),
        ),
    ]
