# Generated by Django 4.2 on 2024-08-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='verifyphone',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
