# Generated by Django 4.2 on 2024-08-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_telegramuser_phone_alter_verifyphone_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
