# Generated by Django 4.2 on 2024-08-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_info_alter_bonus_code_alter_storephone_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
