# Generated by Django 4.2 on 2024-08-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_store_name_ru_store_name_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='image',
        ),
        migrations.RemoveField(
            model_name='store',
            name='link',
        ),
    ]
