# Generated by Django 4.2 on 2024-09-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_userpointimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpoint',
            name='is_active',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
