# Generated by Django 4.2 on 2024-09-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_userpoint_is_active_telegramuser_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='has_product',
            field=models.BooleanField(default=False),
        ),
    ]
