name: Docker CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
#    - uses: actions/checkout@v3
#
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v3

    - name: Build Docker image and Push the image to DockerHUB
      run: | 
        docker build -t ${{ secrets.DOCKER_USERNAME }}/leo-back .
        docker push ${{ secrets.DOCKER_USERNAME }}/leo-back

    - name: Deploy Docker container
      run: |
        docker stop leo-back || true
        docker rm leo-back || true
        docker run --restart unless-stopped --name leo-back -dp 8082:8000 -v /home/ubuntu/leo/media:/app/media ${{ secrets.DOCKER_USERNAME }}/leo-back

